Create Controller
enocol/Blogger pull request #6
Opened 2024-01-22 18:45 UTC by enocol

In this mile stone, the followig was achieved:
- A Users controller was created
- Actions or methods for the following was create
      - Method to get all users as the index of the page
      - Method  to get a specific user with and ID
      - Method to get all post for a specific user
      - Methos to get a specific post for a specific user 
- Routes for the following url parameters were created:
     - Routers to get all users as index page
     - Routes to get a particular user
     - Route to get all post for a particular user
     - Route to get a specific post for a specific user.

2024-01-22 19:36 UTC, IngDavidTM requested changes
## Hi @enocol 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [ ] You've performed well :+1:, but upon attempting to migrate the database, I encountered the following error. Kindly address and resolve this issue, please.

![Screenshot from 2024-01-22 14-32-18](https://github.com/enocol/Blogger/assets/105117832/5c4e2d08-9020-4f78-856e-529e11cf47cb)


- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-22 19:36 UTC, IngDavidTM commented on app/controllers/users_controller.rb
- [ ] You performed exceptionally well; however, as part of the project specifications, it is necessary to include a posts_controller with both #index and #show actions in your project :+1:.

2024-01-22 19:36 UTC, IngDavidTM commented on app/views/users/show_user_post.html.erb
- [ ] Well done on crafting the views for users. However, as a project prerequisite, ensure you have matching view files for each controller action, similar to the following:

```ruby
    # app/views/users/index.html.erb
    # app/views/users/show.html.erb

    # app/views/posts/index.html.erb
    # app/views/posts/show.html.erb
```

2024-01-23 01:59 UTC, Olamarx requested changes
Hi @enocol, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- GitFlow ✅
- Descriptive and professional PR ✅
- Linters are working properly ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-23 01:59 UTC, Olamarx commented on config/routes.rb
> +  get '/users', to: 'users#index', as: 'users'
- [OPTIONAL] I would recommend you to use fewer code as 
```
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
```

With this, we will mean the same as you've written

2024-01-23 01:59 UTC, Olamarx commented on app/controllers/users_controller.rb
> * [ ]  You performed exceptionally well; however, as part of the project specifications, it is necessary to include a posts_controller with both #index and #show actions in your project 👍.

- [ ] As the previous reviewer noted, you need to add the post_controller too as required in this milestone. The file should have the index and show methods as you have it for the users_controller

2024-01-23 02:09 UTC, enocol commented
Hi @Olamarx. Thanks for reviewing my project. Just to get more clarification. You mentioned that as requested by the previous reviewer, thats it necceserry to have a Post_controller file with a show and index action. My project actually has this controller as specified actions as show in the image below:
![image](https://github.com/enocol/Blogger/assets/129378066/37d5b5ef-a9ea-4d91-9175-52843c849255)

Could you explain futher it there is something missing in these actions please. Thanks

2024-01-23 07:24 UTC, Ibizugbe approved these changes
Hi @enocol 👋🏼👋🏼👋🏼, 

![approved](https://github.com/enocol/Blogger/assets/64643995/cc5f13a7-fe78-4109-801f-0d7c0b7e0298)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅

- [x] Index and show actions for post controller have been added👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-23 09:20 UTC, merged